"""AO31 runtime governance contract and state registries."""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping

from agentops.core.errors import AgentOpsError
from agentops.models.runtime import (
    ContractRegistryEntry,
    ErrorCodeDefinition,
    StateRegistryEntry,
)


DOMAIN_OWNERS = {
    "AgentOps",
    "Agent Runtime",
    "Agent Store",
    "Ai_AutoSDLC",
    "Contract Registry",
}

CONTRACT_PARTIES = DOMAIN_OWNERS | {"Runtime", "Ops", "Store", "Policy Service"}


def _entry(
    contract_id: str,
    *,
    domain_owner: str,
    producer: str,
    consumers: tuple[str, ...],
    schema_version: str,
    required_fields: tuple[str, ...],
    optional_fields: tuple[str, ...] = (),
    enum_fields: dict[str, tuple[str, ...]] | None = None,
    state_registry_refs: tuple[str, ...] = (),
    error_codes: tuple[str, ...],
    contract_tests: tuple[str, ...],
    compatibility_policy: str = "no_breaking_in_p0",
) -> ContractRegistryEntry:
    return ContractRegistryEntry(
        contract_id=contract_id,
        domain_owner=domain_owner,
        producer=producer,
        consumers=consumers,
        schema_version=schema_version,
        required_fields=frozenset(required_fields),
        optional_fields=frozenset(optional_fields),
        enum_fields={
            key: frozenset(values) for key, values in (enum_fields or {}).items()
        },
        state_registry_refs=state_registry_refs,
        error_codes=error_codes,
        contract_tests=contract_tests,
        compatibility_policy=compatibility_policy,
    )


CONTRACT_REGISTRY: dict[str, ContractRegistryEntry] = {
    "runtime_run.v1": _entry(
        "runtime_run.v1",
        domain_owner="Agent Runtime",
        producer="Runtime",
        consumers=("AgentOps", "Agent Store"),
        schema_version="runtime_run.v1",
        required_fields=(
            "runtime_id",
            "runtime_version",
            "execution_environment",
            "session_id",
            "run_id",
            "attempt_no",
            "agent_id",
            "version",
            "trigger_source",
            "isolation_profile",
            "policy_bundle_version",
            "status",
            "terminal_reason",
        ),
        optional_fields=("parent_run_id",),
        enum_fields={
            "status": (
                "created",
                "running",
                "approval_paused",
                "succeeded",
                "failed",
                "timeout",
                "cancelled",
                "blocked",
            ),
            "execution_environment": ("local", "managed", "ci", "unknown"),
        },
        state_registry_refs=(
            "created",
            "running",
            "approval_paused",
            "succeeded",
            "failed",
            "cancelled",
            "timeout",
            "blocked",
        ),
        error_codes=("RUNTIME_RUN_INVALID", "RUNTIME_RUN_STATE_INVALID"),
        contract_tests=("AO31-CT-001", "AO31-CT-003"),
    ),
    "trace_span.v1": _entry(
        "trace_span.v1",
        domain_owner="Agent Runtime",
        producer="Runtime",
        consumers=("AgentOps",),
        schema_version="trace_span.v1",
        required_fields=(
            "trace_id",
            "span_id",
            "parent_span_id",
            "run_id",
            "span_kind",
            "operation_name",
            "status_code",
            "start_time",
            "end_time",
            "attempt_no",
            "input_ref",
            "output_ref",
            "token_usage",
            "cost_estimate",
            "grant_id",
            "guardrail_result_refs",
            "error_code",
            "retryable",
        ),
        enum_fields={
            "span_kind": (
                "agent",
                "workflow",
                "model",
                "tool",
                "retrieval",
                "handoff",
                "approval",
                "guardrail",
                "artifact",
                "system",
            ),
            "status_code": ("ok", "error", "unset", "blocked", "waiting"),
        },
        state_registry_refs=("trace_pending", "degraded"),
        error_codes=("TRACE_SPAN_INVALID", "TRACE_SPAN_KIND_UNSUPPORTED"),
        contract_tests=("AO31-CT-001", "AO31-CT-004", "AO31-CT-005"),
    ),
    "guardrail_result.v1": _entry(
        "guardrail_result.v1",
        domain_owner="Agent Runtime",
        producer="Runtime",
        consumers=("AgentOps", "Agent Store"),
        schema_version="guardrail_result.v1",
        required_fields=(
            "guardrail_result_id",
            "run_id",
            "trace_id",
            "span_id",
            "attempt_no",
            "guardrail_id",
            "status",
            "severity",
            "reason_code",
            "policy_version",
            "evidence_ref",
        ),
        enum_fields={
            "status": ("passed", "warn", "blocked", "failed"),
            "severity": ("info", "warning", "critical"),
        },
        state_registry_refs=("blocked", "degraded"),
        error_codes=("GUARDRAIL_RESULT_INVALID",),
        contract_tests=("AO33-CT-005", "AO33-CT-006"),
    ),
    "sdlc_trace_event.v1": _entry(
        "sdlc_trace_event.v1",
        domain_owner="Ai_AutoSDLC",
        producer="Ai_AutoSDLC",
        consumers=("AgentOps",),
        schema_version="sdlc_trace_event.v1",
        required_fields=(
            "sdlc_event_id",
            "run_id",
            "trace_id",
            "span_id",
            "parent_span_id",
            "attempt_no",
            "sdlc_event_type",
            "stage_name",
            "status",
            "started_at",
            "ended_at",
            "artifact_ref",
            "evidence_ref",
            "violation_code",
        ),
        enum_fields={
            "sdlc_event_type": (
                "stage",
                "gate",
                "verification",
                "artifact",
                "violation",
            ),
            "status": (
                "started",
                "passed",
                "failed",
                "blocked",
                "skipped",
                "emitted",
            ),
        },
        state_registry_refs=("degraded", "schema_rejected"),
        error_codes=("SDLC_TRACE_EVENT_INVALID", "TRACE_PARENT_MISSING"),
        contract_tests=("AO34-CT-001", "AO34-CT-004", "AO34-CT-005"),
    ),
    "event_envelope.v1": _entry(
        "event_envelope.v1",
        domain_owner="Contract Registry",
        producer="Runtime",
        consumers=("AgentOps",),
        schema_version="event_envelope.v1",
        required_fields=(
            "event_id",
            "schema_version",
            "event_type",
            "event_type_version",
            "timestamp",
            "integration_mode",
            "enterprise_state",
            "sequence_no",
            "idempotency_key",
            "source_trust",
            "signature",
            "data_classification",
            "redaction_policy",
            "payload_hash",
            "payload_ref",
        ),
        enum_fields={
            "source_trust": ("verified", "signed", "unsigned", "suspected"),
            "integration_mode": (
                "standalone",
                "enterprise_managed",
                "custom_sink",
                "unknown",
            ),
        },
        state_registry_refs=("schema_rejected", "signature_failed"),
        error_codes=(
            "EVENT_SCHEMA_UNSUPPORTED",
            "EVENT_SIGNATURE_INVALID",
            "EVENT_IDEMPOTENCY_CONFLICT",
        ),
        contract_tests=("AO31-CT-001", "AO31-CT-002"),
    ),
    "runtime_outbox_receipt.v1": _entry(
        "runtime_outbox_receipt.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Runtime", "Ai_AutoSDLC"),
        schema_version="runtime_outbox_receipt.v1",
        required_fields=(
            "batch_id",
            "outbox_id",
            "producer",
            "accepted_count",
            "deduplicated_count",
            "stale_count",
            "rejected_count",
            "dlq_count",
            "item_results",
            "audit_id",
        ),
        enum_fields={
            "outbox_state": (
                "delivered",
                "delivered_with_diagnostics",
                "replayed",
                "rejected",
            )
        },
        state_registry_refs=("out_of_order_ignored", "schema_rejected"),
        error_codes=("OUTBOX_SEQUENCE_STALE", "EVENT_IDEMPOTENCY_CONFLICT"),
        contract_tests=("AO34-CT-001", "AO34-CT-002", "AO34-CT-003"),
    ),
    "policy_decision.v1": _entry(
        "policy_decision.v1",
        domain_owner="AgentOps",
        producer="Policy Service",
        consumers=("Runtime", "Agent Store"),
        schema_version="policy_decision.v1",
        required_fields=(
            "decision_id",
            "request_id",
            "subject",
            "resource",
            "action",
            "decision",
            "reason_code",
            "policy_set_version",
            "obligations",
            "constraints",
            "ttl",
            "fallback_action",
        ),
        enum_fields={
            "decision": (
                "allow",
                "warn",
                "approval_required",
                "block",
                "policy_unavailable",
            ),
            "fallback_action": ("allow", "warn", "require_online", "block"),
        },
        state_registry_refs=("blocked", "policy_unavailable"),
        error_codes=("CONTRACT_ENUM_UNREGISTERED", "POLICY_SCOPE_REQUIRED"),
        contract_tests=("AO31-CT-001", "AO31-CT-006"),
    ),
    "capability_grant.v1": _entry(
        "capability_grant.v1",
        domain_owner="AgentOps",
        producer="Policy Service",
        consumers=("Runtime", "Agent Store"),
        schema_version="capability_grant.v1",
        required_fields=(
            "grant_id",
            "decision_id",
            "agent_id",
            "version",
            "artifact_hash",
            "installation_id",
            "device_id",
            "user_id",
            "session_id",
            "run_id",
            "skill_id",
            "resource_scope",
            "remaining_uses",
            "offline_allowed",
            "expires_at",
            "signature",
            "key_id",
        ),
        error_codes=("GRANT_EXPIRED", "GRANT_REVOKED"),
        contract_tests=("AO31-CT-001",),
    ),
    "approval.v1": _entry(
        "approval.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Runtime", "Agent Store", "AgentOps"),
        schema_version="approval.v1",
        required_fields=(
            "approval_id",
            "requested_by",
            "on_behalf_of",
            "approver_policy_ref",
            "resource_scope",
            "risk_reason",
            "pause_token",
            "resume_token",
            "sla_due_at",
            "decision",
            "decision_reason",
            "expires_at",
        ),
        enum_fields={
            "decision": ("pending", "approved", "rejected", "expired", "withdrawn")
        },
        state_registry_refs=("approval_paused",),
        error_codes=("APPROVAL_EXPIRED", "APPROVAL_SCOPE_DENIED"),
        contract_tests=("AO31-CT-001", "AO31-CT-006"),
    ),
    "approval_operation.v1": _entry(
        "approval_operation.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Policy Service", "Agent Store"),
        schema_version="approval_operation.v1",
        required_fields=(
            "operation_id",
            "approval_id",
            "operation",
            "actor",
            "state_before",
            "state_after",
            "summary",
            "audit_id",
        ),
        optional_fields=(
            "reason",
            "required_materials",
            "supplemental_materials",
            "sla_state",
            "notification_intent",
            "break_glass_reason",
            "operation_sequence",
        ),
        enum_fields={
            "operation": (
                "request_input",
                "request_more_info",
                "approve",
                "reject",
                "expire",
                "withdraw",
                "escalate",
                "revoke",
                "break_glass_approve",
            ),
            "state_after": (
                "pending",
                "needs_input",
                "needs_more_info",
                "approved",
                "rejected",
                "expired",
                "withdrawn",
                "escalated",
                "revoked",
            ),
        },
        state_registry_refs=("approval_paused",),
        error_codes=(
            "APPROVAL_STATE_INVALID",
            "APPROVAL_SELF_APPROVAL_DENIED",
            "APPROVAL_ACTION_UNSUPPORTED",
        ),
        contract_tests=("AO36-CT-001", "AO36-CT-002"),
        compatibility_policy="p1_backward_compatible",
    ),
    "policy_set_version.v1": _entry(
        "policy_set_version.v1",
        domain_owner="AgentOps",
        producer="Policy Service",
        consumers=("Ops", "Runtime", "Agent Store"),
        schema_version="policy_set_version.v1",
        required_fields=(
            "policy_set_version",
            "state",
            "risk_templates",
            "fallback_action",
            "deny_priority",
            "summary",
            "audit_id",
        ),
        optional_fields=(
            "traffic_scope",
            "active_version",
            "rollback_from",
            "rollback_reason",
            "owner",
            "policy_set_version_record_id",
            "transition_sequence",
        ),
        enum_fields={
            "state": ("draft", "canary", "active", "rolled_back", "retired"),
            "fallback_action": ("allow", "warn", "require_online", "block"),
        },
        state_registry_refs=("blocked", "policy_unavailable"),
        error_codes=("POLICY_VERSION_INVALID", "POLICY_ROLLBACK_UNSAFE"),
        contract_tests=("AO36-CT-001", "AO36-CT-003"),
        compatibility_policy="p1_backward_compatible",
    ),
    "policy_operations_projection.v1": _entry(
        "policy_operations_projection.v1",
        domain_owner="AgentOps",
        producer="Policy Service",
        consumers=("Ops", "Runtime", "Agent Store"),
        schema_version="policy_operations_projection.v1",
        required_fields=(
            "active_version",
            "versions",
            "summary",
            "audit_id",
        ),
        optional_fields=(),
        state_registry_refs=("blocked", "policy_unavailable"),
        error_codes=("POLICY_VERSION_INVALID", "POLICY_ROLLBACK_UNSAFE"),
        contract_tests=("AO36-CT-001", "AO36-CT-003"),
        compatibility_policy="p1_backward_compatible",
    ),
    "grant_lifecycle.v1": _entry(
        "grant_lifecycle.v1",
        domain_owner="AgentOps",
        producer="Policy Service",
        consumers=("Ops", "Runtime", "Agent Store"),
        schema_version="grant_lifecycle.v1",
        required_fields=(
            "grant_id",
            "status",
            "binding",
            "remaining_uses",
            "consumption_summary",
            "impact_summary",
            "audit_id",
        ),
        optional_fields=(
            "expires_at",
            "revoked_at",
            "revoked_by",
            "revocation_reason",
            "offline_allowed",
            "owner_notification_state",
        ),
        enum_fields={
            "status": ("active", "revoked", "expired", "exhausted"),
            "owner_notification_state": ("not_required", "pending", "sent"),
        },
        state_registry_refs=("blocked", "approval_paused"),
        error_codes=("GRANT_EXPIRED", "GRANT_REVOKED", "GRANT_EXHAUSTED"),
        contract_tests=("AO36-CT-001", "AO36-CT-004"),
        compatibility_policy="p1_backward_compatible",
    ),
    "evidence_summary.v1": _entry(
        "evidence_summary.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Agent Store", "Ai_AutoSDLC"),
        schema_version="evidence_summary.v1",
        required_fields=(
            "run_id",
            "trace_id",
            "evidence_level",
            "source_event_ids",
            "freshness",
            "valid_until",
            "confidence",
            "missing_dimensions",
            "redaction_state",
            "raw_access_state",
            "degraded_reason",
        ),
        error_codes=("RAW_ACCESS_REQUIRED", "EVIDENCE_SUMMARY_EXPIRED"),
        contract_tests=("AO31-CT-001",),
    ),
    "health_summary.v1": _entry(
        "health_summary.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Agent Store", "Runtime"),
        schema_version="health_summary.v1",
        required_fields=(
            "agent_id",
            "version",
            "health_template_id",
            "calculation_window",
            "sample_size",
            "success_rate",
            "failure_rate",
            "evidence_completeness",
            "policy_block_count",
            "confidence",
            "valid_until",
            "recommended_action",
            "appeal_state",
        ),
        enum_fields={
            "recommended_action": (
                "usable",
                "watching",
                "use_with_caution",
                "disable_recommended",
                "disabled",
                "expired",
            )
        },
        error_codes=("HEALTH_SUMMARY_EXPIRED",),
        contract_tests=("AO31-CT-001",),
    ),
    "p0_acceptance_gate.v1": _entry(
        "p0_acceptance_gate.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Agent Store", "Ai_AutoSDLC"),
        schema_version="p0_acceptance_gate.v1",
        required_fields=(
            "gate_id",
            "run_id",
            "agent_id",
            "version",
            "gate_status",
            "required_checks",
            "summary",
            "audit_id",
        ),
        enum_fields={
            "gate_status": ("passed", "failed"),
        },
        state_registry_refs=("degraded", "blocked"),
        error_codes=("P0_ACCEPTANCE_FAILED",),
        contract_tests=("AO35-CT-001", "AO35-CT-002"),
    ),
    "evidence_access_operation.v1": _entry(
        "evidence_access_operation.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Policy Service"),
        schema_version="evidence_access_operation.v1",
        required_fields=(
            "operation_id",
            "evidence_id",
            "requester",
            "reason",
            "approver_scope",
            "raw_access_state",
            "summary",
            "audit_id",
        ),
        optional_fields=(
            "run_id",
            "trace_id",
            "payload_hash",
            "payload_ref",
            "redaction_preview_state",
            "owner_notification_state",
        ),
        enum_fields={
            "raw_access_state": ("requested", "approved", "denied", "expired"),
            "redaction_preview_state": ("ready", "failed", "not_available"),
            "owner_notification_state": ("not_required", "pending", "sent"),
        },
        state_registry_refs=("blocked", "approval_paused"),
        error_codes=("RAW_ACCESS_REQUIRED", "RAW_ACCESS_DENIED"),
        contract_tests=("AO37-CT-001", "AO37-CT-002"),
        compatibility_policy="p1_backward_compatible",
    ),
    "eval_case.v1": _entry(
        "eval_case.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Ai_AutoSDLC"),
        schema_version="eval_case.v1",
        required_fields=(
            "eval_case_id",
            "source_run",
            "privacy_class",
            "owner_team",
            "expected_behavior",
            "scorer_status",
            "audit_id",
        ),
        optional_fields=("evidence_summary", "summary", "status"),
        enum_fields={
            "status": ("needs_review", "ready", "retired"),
            "scorer_status": ("not_started", "passed", "failed", "needs_human_review"),
        },
        state_registry_refs=("failed", "blocked", "degraded"),
        error_codes=("EVAL_CASE_SOURCE_NOT_FAILED", "RUNTIME_RUN_NOT_FOUND"),
        contract_tests=("AO37-CT-001", "AO37-CT-003"),
        compatibility_policy="p1_backward_compatible",
    ),
    "runtime_budget_summary.v1": _entry(
        "runtime_budget_summary.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Agent Store"),
        schema_version="runtime_budget_summary.v1",
        required_fields=(
            "agent_id",
            "version",
            "token_usage",
            "cost_estimate",
            "latency_ms",
            "budget_state",
            "audit_id",
        ),
        optional_fields=("calculation_window", "summary", "recommended_action"),
        enum_fields={
            "budget_state": ("within_budget", "at_risk", "over_budget", "unknown"),
        },
        state_registry_refs=("degraded",),
        error_codes=("BUDGET_SUMMARY_UNAVAILABLE",),
        contract_tests=("AO37-CT-001", "AO37-CT-004"),
        compatibility_policy="p1_backward_compatible",
    ),
    "dlq_operations_projection.v1": _entry(
        "dlq_operations_projection.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Runtime"),
        schema_version="dlq_operations_projection.v1",
        required_fields=(
            "backlog_count",
            "retry_candidates",
            "discard_candidates",
            "error_summary",
            "audit_id",
        ),
        optional_fields=("summary",),
        error_codes=("DLQ_OPERATION_UNAVAILABLE",),
        contract_tests=("AO37-CT-001", "AO37-CT-005"),
        compatibility_policy="p1_backward_compatible",
    ),
    "exporter_operation.v1": _entry(
        "exporter_operation.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops",),
        schema_version="exporter_operation.v1",
        required_fields=(
            "exporter_type",
            "configuration_state",
            "external_write_enabled",
            "dispatch_state",
            "audit_id",
        ),
        optional_fields=("endpoint_ref", "requested_by", "summary"),
        enum_fields={
            "exporter_type": ("otlp", "openinference"),
            "configuration_state": ("not_configured", "configured"),
            "dispatch_state": ("not_started", "dry_run", "blocked"),
        },
        error_codes=("EXPORTER_WRITE_DISABLED",),
        contract_tests=("AO37-CT-001", "AO37-CT-006"),
        compatibility_policy="p1_backward_compatible",
    ),
    "runtime_slo_summary.v1": _entry(
        "runtime_slo_summary.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Agent Store"),
        schema_version="runtime_slo_summary.v1",
        required_fields=(
            "agent_id",
            "version",
            "slo_state",
            "health_summary",
            "budget_summary",
            "recommended_action",
            "audit_id",
        ),
        optional_fields=("dlq_summary", "summary"),
        enum_fields={
            "slo_state": ("healthy", "watching", "at_risk", "breached"),
            "recommended_action": (
                "none",
                "watch",
                "review_budget",
                "open_ops_review",
            ),
        },
        state_registry_refs=("degraded", "blocked"),
        error_codes=("RUNTIME_SLO_UNAVAILABLE",),
        contract_tests=("AO37-CT-001", "AO37-CT-007"),
        compatibility_policy="p1_backward_compatible",
    ),
    "store_governance_projection.v1": _entry(
        "store_governance_projection.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Agent Store", "Ops"),
        schema_version="store_governance_projection.v1",
        required_fields=(
            "agent_id",
            "version",
            "summary_state",
            "appeal_state",
            "owner_notification_state",
            "replacement_suggestion_state",
            "audit_id",
        ),
        optional_fields=("recommended_action", "summary"),
        enum_fields={
            "summary_state": ("fresh", "expired"),
            "appeal_state": ("none", "available", "pending"),
            "owner_notification_state": ("not_required", "pending", "sent"),
            "replacement_suggestion_state": ("not_required", "suggested"),
        },
        error_codes=("STORE_GOVERNANCE_UNAVAILABLE",),
        contract_tests=("AO37-CT-001", "AO37-CT-008"),
        compatibility_policy="p1_backward_compatible",
    ),
    "safe_replay_plan.v1": _entry(
        "safe_replay_plan.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Runtime", "Ai_AutoSDLC"),
        schema_version="safe_replay_plan.v1",
        required_fields=(
            "replay_plan_id",
            "source_run",
            "sandbox_profile",
            "replay_mode",
            "execution_state",
            "summary",
            "audit_id",
        ),
        optional_fields=("evidence_summary", "created_by", "reason", "created_at"),
        enum_fields={
            "replay_mode": ("simulation_only", "shadow_plan"),
            "execution_state": ("not_started", "blocked"),
        },
        state_registry_refs=("failed", "timeout", "blocked", "cancelled", "degraded"),
        error_codes=("RUNTIME_RUN_NOT_FOUND", "REPLAY_SOURCE_NOT_TERMINAL"),
        contract_tests=("AO38-CT-001", "AO38-CT-002"),
        compatibility_policy="p2_backward_compatible",
    ),
    "experiment_plan.v1": _entry(
        "experiment_plan.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Runtime", "Agent Store"),
        schema_version="experiment_plan.v1",
        required_fields=(
            "experiment_plan_id",
            "agent_id",
            "version",
            "variants",
            "rollout_state",
            "summary",
            "audit_id",
        ),
        optional_fields=("owner_team", "hypothesis", "created_at"),
        enum_fields={
            "rollout_state": ("planning", "blocked"),
        },
        state_registry_refs=("degraded", "blocked"),
        error_codes=("EXPERIMENT_VARIANT_UNSAFE",),
        contract_tests=("AO38-CT-001", "AO38-CT-003"),
        compatibility_policy="p2_backward_compatible",
    ),
    "optimizer_recommendation.v1": _entry(
        "optimizer_recommendation.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Agent Store", "Ai_AutoSDLC"),
        schema_version="optimizer_recommendation.v1",
        required_fields=(
            "agent_id",
            "version",
            "source_eval_cases",
            "recommendation_state",
            "recommended_action",
            "summary",
            "audit_id",
        ),
        optional_fields=("evidence_window",),
        enum_fields={
            "recommendation_state": ("ready", "insufficient_evidence"),
            "recommended_action": (
                "no_change",
                "collect_more_samples",
                "prepare_experiment",
                "manual_review",
            ),
        },
        state_registry_refs=("degraded", "blocked"),
        error_codes=("OPTIMIZER_EVIDENCE_REQUIRED",),
        contract_tests=("AO38-CT-001", "AO38-CT-004"),
        compatibility_policy="p2_backward_compatible",
    ),
    "policy_simulation_projection.v1": _entry(
        "policy_simulation_projection.v1",
        domain_owner="AgentOps",
        producer="Policy Service",
        consumers=("Ops", "Runtime", "Agent Store"),
        schema_version="policy_simulation_projection.v1",
        required_fields=(
            "policy_set_version",
            "proposed_change",
            "sample_run_ids",
            "simulation_state",
            "decision_impact_summary",
            "summary",
            "audit_id",
        ),
        optional_fields=("requested_by",),
        enum_fields={
            "simulation_state": ("projected", "insufficient_sample", "blocked"),
        },
        state_registry_refs=("blocked", "policy_unavailable"),
        error_codes=("POLICY_SIMULATION_UNSUPPORTED_ACTION",),
        contract_tests=("AO38-CT-001", "AO38-CT-005"),
        compatibility_policy="p2_backward_compatible",
    ),
    "mcp_a2a_governance_projection.v1": _entry(
        "mcp_a2a_governance_projection.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Runtime", "Agent Store"),
        schema_version="mcp_a2a_governance_projection.v1",
        required_fields=(
            "protocol",
            "endpoint_ref",
            "subject_agent_id",
            "gateway_state",
            "policy_check_state",
            "evidence_state",
            "summary",
            "audit_id",
        ),
        optional_fields=("resource_scope", "requested_by"),
        enum_fields={
            "protocol": ("mcp", "a2a"),
            "gateway_state": ("required", "configured", "blocked"),
            "policy_check_state": ("required", "passed", "blocked"),
            "evidence_state": ("summary_only", "missing", "degraded"),
        },
        state_registry_refs=("blocked", "degraded", "policy_unavailable"),
        error_codes=("MCP_A2A_PROTOCOL_UNSUPPORTED",),
        contract_tests=("AO39-CT-001", "AO39-CT-002"),
        compatibility_policy="p2_backward_compatible",
    ),
    "exporter_ecosystem_projection.v1": _entry(
        "exporter_ecosystem_projection.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops",),
        schema_version="exporter_ecosystem_projection.v1",
        required_fields=(
            "exporters",
            "ecosystem_state",
            "external_write_enabled",
            "summary",
            "audit_id",
        ),
        optional_fields=("requested_by",),
        enum_fields={
            "ecosystem_state": ("not_configured", "configured", "blocked"),
        },
        error_codes=("EXPORTER_ECOSYSTEM_UNSUPPORTED",),
        contract_tests=("AO39-CT-001", "AO39-CT-003"),
        compatibility_policy="p2_backward_compatible",
    ),
    "multi_agent_handoff_evaluation.v1": _entry(
        "multi_agent_handoff_evaluation.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Agent Store", "Ai_AutoSDLC"),
        schema_version="multi_agent_handoff_evaluation.v1",
        required_fields=(
            "agent_id",
            "version",
            "handoff_count",
            "failed_handoff_count",
            "handoff_quality_state",
            "summary",
            "audit_id",
        ),
        optional_fields=("source_run_ids", "handoff_candidates"),
        enum_fields={
            "handoff_quality_state": (
                "insufficient_data",
                "healthy",
                "needs_review",
            ),
        },
        state_registry_refs=("failed", "blocked", "degraded"),
        error_codes=("HANDOFF_EVALUATION_UNAVAILABLE",),
        contract_tests=("AO39-CT-001", "AO39-CT-004"),
        compatibility_policy="p2_backward_compatible",
    ),
    "complex_risk_profile.v1": _entry(
        "complex_risk_profile.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Agent Store"),
        schema_version="complex_risk_profile.v1",
        required_fields=(
            "agent_id",
            "version",
            "risk_profile_state",
            "risk_factors",
            "recommended_action",
            "summary",
            "audit_id",
        ),
        optional_fields=("health_summary", "handoff_evaluation", "dlq_summary"),
        enum_fields={
            "risk_profile_state": ("low", "medium", "high", "critical"),
            "recommended_action": (
                "none",
                "watch",
                "open_ops_review",
                "disable_recommended",
            ),
        },
        state_registry_refs=("blocked", "degraded"),
        error_codes=("RISK_PROFILE_UNAVAILABLE",),
        contract_tests=("AO39-CT-001", "AO39-CT-005"),
        compatibility_policy="p2_backward_compatible",
    ),
    "quality_score_projection.v1": _entry(
        "quality_score_projection.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Agent Store", "Ai_AutoSDLC"),
        schema_version="quality_score_projection.v1",
        required_fields=(
            "agent_id",
            "version",
            "score_template_id",
            "score",
            "quality_state",
            "evidence_level",
            "confidence",
            "missing_evidence",
            "explanation",
            "summary",
            "audit_id",
        ),
        optional_fields=("source_run_ids", "health_summary"),
        enum_fields={
            "quality_state": (
                "healthy",
                "watching",
                "needs_review",
                "critical",
                "insufficient_evidence",
            ),
        },
        state_registry_refs=("degraded", "blocked"),
        error_codes=("QUALITY_SCORE_UNAVAILABLE",),
        contract_tests=("AO40-CT-001", "AO40-CT-002"),
        compatibility_policy="p2_backward_compatible",
    ),
    "adoption_roi_projection.v1": _entry(
        "adoption_roi_projection.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Agent Store"),
        schema_version="adoption_roi_projection.v1",
        required_fields=(
            "agent_id",
            "version",
            "adoption_state",
            "retention_rate",
            "rework_risk",
            "adoption_metrics",
            "review_summary",
            "sampling_review_state",
            "summary",
            "audit_id",
        ),
        optional_fields=("owner_team",),
        enum_fields={
            "adoption_state": (
                "adopted",
                "watching",
                "needs_review",
                "insufficient_data",
            ),
            "rework_risk": ("low", "medium", "high"),
            "sampling_review_state": ("not_started", "pending", "passed", "failed"),
        },
        state_registry_refs=("degraded",),
        error_codes=("ADOPTION_ROI_UNAVAILABLE",),
        contract_tests=("AO40-CT-001", "AO40-CT-003"),
        compatibility_policy="p2_backward_compatible",
    ),
    "lifecycle_recommendation.v1": _entry(
        "lifecycle_recommendation.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Agent Store"),
        schema_version="lifecycle_recommendation.v1",
        required_fields=(
            "agent_id",
            "version",
            "lifecycle_state",
            "recommended_action",
            "owner_notification_state",
            "appeal_state",
            "quality_score",
            "risk_profile",
            "store_governance",
            "summary",
            "audit_id",
        ),
        enum_fields={
            "lifecycle_state": (
                "healthy",
                "watching",
                "review_required",
                "disable_review_recommended",
            ),
            "recommended_action": (
                "none",
                "watch",
                "collect_more_evidence",
                "open_ops_review",
                "open_disable_review",
            ),
            "owner_notification_state": ("not_required", "pending", "sent"),
            "appeal_state": ("none", "available", "pending"),
        },
        state_registry_refs=("degraded", "blocked"),
        error_codes=("LIFECYCLE_RECOMMENDATION_UNAVAILABLE",),
        contract_tests=("AO40-CT-001", "AO40-CT-004"),
        compatibility_policy="p2_backward_compatible",
    ),
    "monthly_quality_report.v1": _entry(
        "monthly_quality_report.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops",),
        schema_version="monthly_quality_report.v1",
        required_fields=(
            "report_period",
            "report_state",
            "agent_summaries",
            "trend_summary",
            "summary",
            "audit_id",
        ),
        optional_fields=("generated_by",),
        enum_fields={
            "report_state": ("ready", "insufficient_data"),
        },
        state_registry_refs=("degraded",),
        error_codes=("MONTHLY_REPORT_UNAVAILABLE",),
        contract_tests=("AO40-CT-001", "AO40-CT-005"),
        compatibility_policy="p2_backward_compatible",
    ),
    "quality_scorer_version.v1": _entry(
        "quality_scorer_version.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Ai_AutoSDLC"),
        schema_version="quality_scorer_version.v1",
        required_fields=(
            "scorer_id",
            "scorer_version",
            "score_template_id",
            "rollout_state",
            "required_evidence",
            "input_boundary",
            "summary",
            "audit_id",
        ),
        optional_fields=("owner_team", "scoring_policy"),
        enum_fields={
            "rollout_state": ("draft", "candidate", "approved", "retired"),
        },
        state_registry_refs=("degraded", "blocked"),
        error_codes=("QUALITY_SCORER_UNAVAILABLE",),
        contract_tests=("AO41-CT-001", "AO41-CT-002"),
        compatibility_policy="p1_backward_compatible",
    ),
    "quality_scorer_comparison.v1": _entry(
        "quality_scorer_comparison.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Ai_AutoSDLC"),
        schema_version="quality_scorer_comparison.v1",
        required_fields=(
            "agent_id",
            "version",
            "source_eval_cases",
            "sample_size",
            "baseline_scorer",
            "candidate_scorer",
            "comparison_state",
            "alignment_delta",
            "safety_impact",
            "recommendation",
            "summary",
            "audit_id",
        ),
        optional_fields=("evidence_window",),
        enum_fields={
            "comparison_state": (
                "insufficient_evidence",
                "ready_for_manual_approval",
                "needs_human_review",
            ),
            "safety_impact": ("improved", "neutral", "negative", "needs_review"),
            "recommendation": (
                "collect_more_samples",
                "submit_for_manual_rollout_approval",
                "needs_human_review",
                "keep_baseline",
            ),
        },
        state_registry_refs=("degraded", "blocked"),
        error_codes=("SCORER_COMPARISON_UNAVAILABLE",),
        contract_tests=("AO41-CT-001", "AO41-CT-003", "AO41-CT-004"),
        compatibility_policy="p1_backward_compatible",
    ),
    "quality_scorer_execution.v1": _entry(
        "quality_scorer_execution.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Ai_AutoSDLC"),
        schema_version="quality_scorer_execution.v1",
        required_fields=(
            "agent_id",
            "version",
            "scorer",
            "source_eval_cases",
            "sample_size",
            "execution_state",
            "outcome_counts",
            "pass_rate",
            "score_summary",
            "evidence_window",
            "recommendation",
            "summary",
            "audit_id",
        ),
        optional_fields=("execution_id", "executed_by", "executed_at"),
        enum_fields={
            "execution_state": (
                "passed",
                "needs_review",
                "failed",
                "blocked",
                "insufficient_evidence",
            ),
            "recommendation": (
                "collect_more_samples",
                "open_manual_scorer_review",
                "submit_for_manual_rollout_approval",
                "keep_baseline",
            ),
        },
        state_registry_refs=("degraded", "blocked"),
        error_codes=("QUALITY_SCORER_EXECUTION_UNAVAILABLE",),
        contract_tests=(
            "AO44-CT-001",
            "AO44-CT-002",
            "AO44-CT-003",
            "AO44-CT-004",
            "AO44-CT-005",
            "AO44-CT-006",
            "AO44-CT-007",
            "AO44-CT-008",
        ),
        compatibility_policy="p1_backward_compatible",
    ),
    "quality_scorer_external_intake.v1": _entry(
        "quality_scorer_external_intake.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Ai_AutoSDLC"),
        schema_version="quality_scorer_external_intake.v1",
        required_fields=(
            "intake_id",
            "idempotency_key",
            "agent_id",
            "version",
            "scorer",
            "source_trust",
            "signature_state",
            "intake_state",
            "payload_hash",
            "accepted_execution_id",
            "summary",
            "audit_id",
        ),
        optional_fields=("producer", "received_at", "sample_size", "pass_rate"),
        enum_fields={
            "source_trust": ("signed", "verified"),
            "signature_state": ("verified", "failed"),
            "intake_state": ("accepted", "deduplicated", "rejected"),
        },
        state_registry_refs=("degraded", "blocked", "signature_failed"),
        error_codes=(
            "QUALITY_SCORER_INTAKE_UNTRUSTED",
            "QUALITY_SCORER_INTAKE_SIGNATURE_INVALID",
            "QUALITY_SCORER_INTAKE_SAMPLE_INVALID",
            "QUALITY_SCORER_INTAKE_RAW_INPUT",
            "QUALITY_SCORER_INTAKE_IDEMPOTENCY_REQUIRED",
            "QUALITY_SCORER_INTAKE_IDEMPOTENCY_CONFLICT",
            "QUALITY_SCORER_INTAKE_THRESHOLD_INVALID",
        ),
        contract_tests=(
            "AO45-CT-001",
            "AO45-CT-002",
            "AO45-CT-003",
            "AO45-CT-004",
            "AO45-CT-005",
            "AO45-CT-006",
            "AO45-CT-007",
            "AO45-CT-008",
            "AO45-CT-009",
            "AO45-CT-010",
            "AO45-CT-011",
            "AO45-CT-012",
            "AO45-CT-013",
            "AO45-CT-014",
            "AO45-CT-015",
            "AO45-CT-016",
            "AO45-CT-017",
        ),
        compatibility_policy="p1_backward_compatible",
    ),
    "quality_scorer_external_intake_http.v1": _entry(
        "quality_scorer_external_intake_http.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Ai_AutoSDLC"),
        schema_version="quality_scorer_external_intake_http.v1",
        required_fields=(
            "route",
            "method",
            "agent_id",
            "version",
            "external_result",
            "idempotency_key",
            "signature",
            "source_trust",
            "receipt",
            "audit_id",
        ),
        optional_fields=("scorer", "producer", "min_eval_cases", "pass_threshold"),
        enum_fields={
            "method": ("POST",),
            "status_code": ("202", "400", "401", "403", "409"),
            "source_trust": ("signed", "verified"),
        },
        state_registry_refs=("degraded", "blocked", "signature_failed"),
        error_codes=(
            "REQUEST_JSON_INVALID",
            "QUALITY_SCORER_INTAKE_HTTP_REQUEST_INVALID",
            "QUALITY_SCORER_INTAKE_UNTRUSTED",
            "QUALITY_SCORER_INTAKE_SIGNATURE_INVALID",
            "QUALITY_SCORER_INTAKE_SAMPLE_INVALID",
            "QUALITY_SCORER_INTAKE_RAW_INPUT",
            "QUALITY_SCORER_INTAKE_IDEMPOTENCY_REQUIRED",
            "QUALITY_SCORER_INTAKE_IDEMPOTENCY_CONFLICT",
            "QUALITY_SCORER_INTAKE_THRESHOLD_INVALID",
            "AGENTOPS_SCOPE_DENIED",
            "UPSTREAM_IDENTITY_REQUIRED",
        ),
        contract_tests=(
            "AO46-CT-001",
            "AO46-CT-002",
            "AO46-CT-003",
            "AO46-CT-004",
            "AO46-CT-005",
        ),
        compatibility_policy="p1_backward_compatible",
    ),
    "quality_scorer_external_intake_readback.v1": _entry(
        "quality_scorer_external_intake_readback.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Ai_AutoSDLC"),
        schema_version="quality_scorer_external_intake_readback.v1",
        required_fields=(
            "route",
            "method",
            "agent_id",
            "version",
            "idempotency_key",
            "receipt",
            "audit_id",
        ),
        optional_fields=("producer", "accepted_execution_id", "received_at"),
        enum_fields={
            "method": ("GET",),
            "status_code": ("200", "400", "403", "404", "409"),
        },
        state_registry_refs=("degraded", "blocked"),
        error_codes=(
            "QUALITY_SCORER_INTAKE_RECEIPT_QUERY_REQUIRED",
            "QUALITY_SCORER_INTAKE_RECEIPT_NOT_FOUND",
            "QUALITY_SCORER_INTAKE_IDEMPOTENCY_CONFLICT",
            "AGENTOPS_SCOPE_DENIED",
            "UPSTREAM_IDENTITY_REQUIRED",
        ),
        contract_tests=(
            "AO47-CT-001",
            "AO47-CT-002",
            "AO47-CT-003",
            "AO47-CT-004",
            "AO47-CT-005",
        ),
        compatibility_policy="p1_backward_compatible",
    ),
    "quality_center_workbench.v1": _entry(
        "quality_center_workbench.v1",
        domain_owner="AgentOps",
        producer="AgentOps",
        consumers=("Ops", "Agent Store"),
        schema_version="quality_center_workbench.v1",
        required_fields=(
            "workbench_state",
            "agent_summaries",
            "scorer_rollout_panel",
            "review_queue",
            "trend_summary",
            "summary",
            "audit_id",
        ),
        optional_fields=("report_period", "generated_by"),
        enum_fields={
            "workbench_state": ("ready", "empty"),
        },
        state_registry_refs=("degraded", "blocked"),
        error_codes=("QUALITY_CENTER_WORKBENCH_UNAVAILABLE",),
        contract_tests=("AO42-CT-001", "AO42-CT-002", "AO42-CT-003"),
        compatibility_policy="p1_backward_compatible",
    ),
}


def _state(
    machine_value: str,
    *,
    display_name: str,
    plain_language_explanation: str,
    severity: str,
    primary_action: str,
    secondary_action: str | None = None,
    terminal_state: bool = False,
    allowed_next_states: tuple[str, ...] = (),
    audit_required: bool = True,
    owner: str = "AgentOps",
) -> StateRegistryEntry:
    return StateRegistryEntry(
        machine_value=machine_value,
        display_name=display_name,
        plain_language_explanation=plain_language_explanation,
        severity=severity,
        primary_action=primary_action,
        secondary_action=secondary_action,
        terminal_state=terminal_state,
        allowed_next_states=allowed_next_states,
        audit_required=audit_required,
        owner=owner,
        expected_display_name=display_name,
    )


STATE_REGISTRY: dict[str, StateRegistryEntry] = {
    "created": _state(
        "created",
        display_name="已创建",
        plain_language_explanation="Runtime 已创建运行记录，尚未开始执行。",
        severity="info",
        primary_action="查看链路",
        allowed_next_states=("running", "blocked", "cancelled", "timeout"),
        owner="Agent Runtime",
    ),
    "running": _state(
        "running",
        display_name="运行中",
        plain_language_explanation="Agent 正在 Runtime 中执行。",
        severity="info",
        primary_action="查看链路",
        allowed_next_states=(
            "approval_paused",
            "succeeded",
            "failed",
            "cancelled",
            "timeout",
            "blocked",
        ),
        owner="Agent Runtime",
    ),
    "approval_paused": _state(
        "approval_paused",
        display_name="等待审批",
        plain_language_explanation="运行已暂停，等待审批通过后才能继续。",
        severity="warning",
        primary_action="查看审批进度",
        secondary_action="撤回申请",
        allowed_next_states=("running", "blocked", "failed"),
    ),
    "succeeded": _state(
        "succeeded",
        display_name="成功",
        plain_language_explanation="本次运行已经完成。",
        severity="success",
        primary_action="查看摘要",
        terminal_state=True,
        owner="Agent Runtime",
    ),
    "failed": _state(
        "failed",
        display_name="失败",
        plain_language_explanation="本次运行失败，需要查看错误和重试条件。",
        severity="critical",
        primary_action="查看错误",
        terminal_state=True,
        owner="Agent Runtime",
    ),
    "cancelled": _state(
        "cancelled",
        display_name="已取消",
        plain_language_explanation="本次运行已被用户或系统取消。",
        severity="info",
        primary_action="查看记录",
        terminal_state=True,
        owner="Agent Runtime",
    ),
    "timeout": _state(
        "timeout",
        display_name="已超时",
        plain_language_explanation="本次运行超过允许时间。",
        severity="warning",
        primary_action="查看超时原因",
        terminal_state=True,
        owner="Agent Runtime",
    ),
    "blocked": _state(
        "blocked",
        display_name="已阻断",
        plain_language_explanation="运行被策略、权限或安全规则阻断。",
        severity="critical",
        primary_action="查看原因",
        secondary_action="发起申诉",
        terminal_state=True,
    ),
    "trace_pending": _state(
        "trace_pending",
        display_name="执行记录待上报",
        plain_language_explanation="Runtime 已产生运行记录，但链路还未完整送达 AgentOps。",
        severity="warning",
        primary_action="重试上报",
        secondary_action="查看诊断",
        audit_required=False,
    ),
    "degraded": _state(
        "degraded",
        display_name="已降级",
        plain_language_explanation="由于证据、签名、链路或权限不完整，只能按降级事实展示。",
        severity="warning",
        primary_action="查看降级原因",
    ),
    "schema_rejected": _state(
        "schema_rejected",
        display_name="格式被拒绝",
        plain_language_explanation="上报内容不符合当前支持的 schema。",
        severity="critical",
        primary_action="查看字段错误",
    ),
    "signature_failed": _state(
        "signature_failed",
        display_name="签名失败",
        plain_language_explanation="上报签名缺失或验证失败，不能进入可信事实。",
        severity="critical",
        primary_action="重新签名上报",
    ),
    "out_of_order_ignored": _state(
        "out_of_order_ignored",
        display_name="乱序已忽略",
        plain_language_explanation="较旧的 outbox 事件已被接收并忽略，不能覆盖更新事实。",
        severity="info",
        primary_action="查看最新事实",
        audit_required=False,
    ),
    "policy_unavailable": _state(
        "policy_unavailable",
        display_name="运行规则服务不可用",
        plain_language_explanation="策略服务暂时不可用，高风险动作不能默认为安全。",
        severity="warning",
        primary_action="稍后重试",
    ),
}


ERROR_CODE_REGISTRY: dict[str, ErrorCodeDefinition] = {
    "CONTRACT_OWNER_REQUIRED": ErrorCodeDefinition(
        "CONTRACT_OWNER_REQUIRED",
        500,
        False,
        "契约缺少负责人。",
        "Contract registry entries require domain_owner.",
        True,
    ),
    "CONTRACT_PARTY_UNREGISTERED": ErrorCodeDefinition(
        "CONTRACT_PARTY_UNREGISTERED",
        500,
        False,
        "契约生产方或消费方未登记。",
        "Contract producer/consumer must be registered.",
        True,
    ),
    "CONTRACT_ENUM_UNREGISTERED": ErrorCodeDefinition(
        "CONTRACT_ENUM_UNREGISTERED",
        400,
        False,
        "字段值未登记。",
        "Field value is outside the registered enum.",
        True,
    ),
    "STATE_DISPLAY_MISMATCH": ErrorCodeDefinition(
        "STATE_DISPLAY_MISMATCH",
        500,
        False,
        "状态展示定义不一致。",
        "State registry display name drift detected.",
        True,
    ),
    "REQUEST_JSON_INVALID": ErrorCodeDefinition(
        "REQUEST_JSON_INVALID",
        400,
        False,
        "请求体必须是 JSON。",
        "Request body must be JSON.",
        False,
    ),
    "UPSTREAM_IDENTITY_REQUIRED": ErrorCodeDefinition(
        "UPSTREAM_IDENTITY_REQUIRED",
        401,
        False,
        "生产模式需要上游 IAM/RBAC 身份证明。",
        "Production mode requires upstream IAM/RBAC identity.",
        False,
    ),
    "AGENTOPS_SCOPE_DENIED": ErrorCodeDefinition(
        "AGENTOPS_SCOPE_DENIED",
        403,
        False,
        "上游身份缺少执行该 AgentOps API 的权限。",
        "Upstream identity is missing the required AgentOps API scope.",
        False,
    ),
    "EVENT_SCHEMA_UNSUPPORTED": ErrorCodeDefinition(
        "EVENT_SCHEMA_UNSUPPORTED",
        400,
        False,
        "事件格式版本不支持。",
        "Unsupported event schema_version.",
        True,
    ),
    "EVENT_SIGNATURE_INVALID": ErrorCodeDefinition(
        "EVENT_SIGNATURE_INVALID",
        401,
        False,
        "事件签名无效。",
        "Invalid runtime event signature.",
        True,
    ),
    "EVENT_IDEMPOTENCY_CONFLICT": ErrorCodeDefinition(
        "EVENT_IDEMPOTENCY_CONFLICT",
        409,
        False,
        "幂等键冲突。",
        "Idempotency key maps to a different payload.",
        True,
    ),
    "TRACE_PARENT_MISSING": ErrorCodeDefinition(
        "TRACE_PARENT_MISSING",
        202,
        True,
        "执行链路缺少父步骤。",
        "Trace span parent is missing; timeline must be degraded.",
        False,
    ),
    "TRACE_SPAN_KIND_UNSUPPORTED": ErrorCodeDefinition(
        "TRACE_SPAN_KIND_UNSUPPORTED",
        400,
        False,
        "执行步骤类型不支持。",
        "Trace span_kind is not registered.",
        True,
    ),
    "OUTBOX_SEQUENCE_STALE": ErrorCodeDefinition(
        "OUTBOX_SEQUENCE_STALE",
        202,
        False,
        "较旧 outbox 事件已忽略。",
        "Older outbox event sequence was ignored.",
        False,
    ),
    "SDLC_TRACE_EVENT_INVALID": ErrorCodeDefinition(
        "SDLC_TRACE_EVENT_INVALID",
        400,
        False,
        "SDLC trace 事件无效。",
        "Ai_AutoSDLC trace event failed bridge validation.",
        True,
    ),
    "P0_ACCEPTANCE_FAILED": ErrorCodeDefinition(
        "P0_ACCEPTANCE_FAILED",
        409,
        False,
        "P0 端到端验收未通过。",
        "One or more P0 acceptance gate checks failed.",
        True,
    ),
    "EVAL_CASE_SOURCE_NOT_FAILED": ErrorCodeDefinition(
        "EVAL_CASE_SOURCE_NOT_FAILED",
        400,
        False,
        "只有失败或阻断运行可以沉淀为评测样本。",
        "Only failed, blocked, cancelled, timeout, or degraded runs can seed EvalCase.",
        True,
    ),
    "BUDGET_SUMMARY_UNAVAILABLE": ErrorCodeDefinition(
        "BUDGET_SUMMARY_UNAVAILABLE",
        404,
        False,
        "预算摘要暂不可用。",
        "Runtime budget summary is unavailable.",
        False,
    ),
    "DLQ_OPERATION_UNAVAILABLE": ErrorCodeDefinition(
        "DLQ_OPERATION_UNAVAILABLE",
        404,
        False,
        "DLQ 操作投影暂不可用。",
        "DLQ operations projection is unavailable.",
        False,
    ),
    "EXPORTER_WRITE_DISABLED": ErrorCodeDefinition(
        "EXPORTER_WRITE_DISABLED",
        403,
        False,
        "Exporter 写入在当前阶段被禁用。",
        "External exporter writes are disabled in this phase.",
        True,
    ),
    "STORE_GOVERNANCE_UNAVAILABLE": ErrorCodeDefinition(
        "STORE_GOVERNANCE_UNAVAILABLE",
        404,
        False,
        "Store 治理投影暂不可用。",
        "Store governance projection is unavailable.",
        False,
    ),
    "REPLAY_SOURCE_NOT_TERMINAL": ErrorCodeDefinition(
        "REPLAY_SOURCE_NOT_TERMINAL",
        400,
        False,
        "只有已结束运行可以生成安全重放计划。",
        "Safe replay planning requires a terminal source run.",
        True,
    ),
    "EXPERIMENT_VARIANT_UNSAFE": ErrorCodeDefinition(
        "EXPERIMENT_VARIANT_UNSAFE",
        400,
        False,
        "实验变体只能登记摘要引用，不能包含原始 prompt 或密钥。",
        "Experiment variants must use safe refs or hashes instead of raw prompts or secrets.",
        True,
    ),
    "OPTIMIZER_EVIDENCE_REQUIRED": ErrorCodeDefinition(
        "OPTIMIZER_EVIDENCE_REQUIRED",
        404,
        False,
        "优化建议需要评测样本或运行摘要证据。",
        "Optimizer recommendation requires EvalCase or runtime summary evidence.",
        False,
    ),
    "POLICY_SIMULATION_UNSUPPORTED_ACTION": ErrorCodeDefinition(
        "POLICY_SIMULATION_UNSUPPORTED_ACTION",
        400,
        False,
        "当前策略模拟动作不受支持。",
        "Policy simulation only supports projected governance changes in this phase.",
        True,
    ),
    "MCP_A2A_PROTOCOL_UNSUPPORTED": ErrorCodeDefinition(
        "MCP_A2A_PROTOCOL_UNSUPPORTED",
        400,
        False,
        "MCP/A2A 协议类型不受支持。",
        "MCP/A2A governance projection only supports registered protocols.",
        True,
    ),
    "EXPORTER_ECOSYSTEM_UNSUPPORTED": ErrorCodeDefinition(
        "EXPORTER_ECOSYSTEM_UNSUPPORTED",
        400,
        False,
        "Exporter 生态类型不受支持。",
        "Exporter ecosystem projection only supports registered exporter types.",
        True,
    ),
    "HANDOFF_EVALUATION_UNAVAILABLE": ErrorCodeDefinition(
        "HANDOFF_EVALUATION_UNAVAILABLE",
        404,
        False,
        "多 Agent handoff 评测暂不可用。",
        "Multi-agent handoff evaluation is unavailable.",
        False,
    ),
    "RISK_PROFILE_UNAVAILABLE": ErrorCodeDefinition(
        "RISK_PROFILE_UNAVAILABLE",
        404,
        False,
        "复杂风险画像暂不可用。",
        "Complex risk profile is unavailable.",
        False,
    ),
    "QUALITY_SCORE_UNAVAILABLE": ErrorCodeDefinition(
        "QUALITY_SCORE_UNAVAILABLE",
        404,
        False,
        "质量评分投影暂不可用。",
        "Quality score projection is unavailable.",
        False,
    ),
    "ADOPTION_ROI_UNAVAILABLE": ErrorCodeDefinition(
        "ADOPTION_ROI_UNAVAILABLE",
        404,
        False,
        "采纳与 ROI 投影暂不可用。",
        "Adoption ROI projection is unavailable.",
        False,
    ),
    "LIFECYCLE_RECOMMENDATION_UNAVAILABLE": ErrorCodeDefinition(
        "LIFECYCLE_RECOMMENDATION_UNAVAILABLE",
        404,
        False,
        "生命周期建议暂不可用。",
        "Lifecycle recommendation is unavailable.",
        False,
    ),
    "MONTHLY_REPORT_UNAVAILABLE": ErrorCodeDefinition(
        "MONTHLY_REPORT_UNAVAILABLE",
        404,
        False,
        "月度质量报告暂不可用。",
        "Monthly quality report is unavailable.",
        False,
    ),
    "QUALITY_SCORER_UNAVAILABLE": ErrorCodeDefinition(
        "QUALITY_SCORER_UNAVAILABLE",
        404,
        False,
        "质量评分器版本暂不可用。",
        "Quality scorer version is unavailable.",
        False,
    ),
    "SCORER_COMPARISON_UNAVAILABLE": ErrorCodeDefinition(
        "SCORER_COMPARISON_UNAVAILABLE",
        400,
        False,
        "评分器版本对比暂不可用。",
        "Scorer comparison is unavailable.",
        False,
    ),
    "QUALITY_SCORER_EXECUTION_UNAVAILABLE": ErrorCodeDefinition(
        "QUALITY_SCORER_EXECUTION_UNAVAILABLE",
        400,
        False,
        "质量评分器执行证据暂不可用。",
        "Quality scorer execution evidence is unavailable.",
        False,
    ),
    "QUALITY_SCORER_INTAKE_UNTRUSTED": ErrorCodeDefinition(
        "QUALITY_SCORER_INTAKE_UNTRUSTED",
        403,
        False,
        "外部质量评分器接入来源不可信。",
        "External quality scorer intake source is not trusted.",
        False,
    ),
    "QUALITY_SCORER_INTAKE_SIGNATURE_INVALID": ErrorCodeDefinition(
        "QUALITY_SCORER_INTAKE_SIGNATURE_INVALID",
        401,
        False,
        "外部质量评分器接入签名无效。",
        "External quality scorer intake signature is invalid.",
        False,
    ),
    "QUALITY_SCORER_INTAKE_SAMPLE_INVALID": ErrorCodeDefinition(
        "QUALITY_SCORER_INTAKE_SAMPLE_INVALID",
        400,
        False,
        "外部质量评分器接入样本边界无效。",
        "External quality scorer intake sample boundary is invalid.",
        False,
    ),
    "QUALITY_SCORER_INTAKE_RAW_INPUT": ErrorCodeDefinition(
        "QUALITY_SCORER_INTAKE_RAW_INPUT",
        400,
        False,
        "外部质量评分器接入只接受摘要输入。",
        "External quality scorer intake accepts summary-only input.",
        False,
    ),
    "QUALITY_SCORER_INTAKE_IDEMPOTENCY_REQUIRED": ErrorCodeDefinition(
        "QUALITY_SCORER_INTAKE_IDEMPOTENCY_REQUIRED",
        400,
        False,
        "外部质量评分器接入必须提供幂等键。",
        "External quality scorer intake requires an idempotency key.",
        False,
    ),
    "QUALITY_SCORER_INTAKE_IDEMPOTENCY_CONFLICT": ErrorCodeDefinition(
        "QUALITY_SCORER_INTAKE_IDEMPOTENCY_CONFLICT",
        409,
        False,
        "外部质量评分器接入幂等键与既有载荷冲突。",
        "External quality scorer intake idempotency key conflicts with an existing payload.",
        False,
    ),
    "QUALITY_SCORER_INTAKE_THRESHOLD_INVALID": ErrorCodeDefinition(
        "QUALITY_SCORER_INTAKE_THRESHOLD_INVALID",
        400,
        False,
        "外部质量评分器接入最小样本阈值无效。",
        "External quality scorer intake minimum sample threshold is invalid.",
        False,
    ),
    "QUALITY_SCORER_INTAKE_HTTP_REQUEST_INVALID": ErrorCodeDefinition(
        "QUALITY_SCORER_INTAKE_HTTP_REQUEST_INVALID",
        400,
        False,
        "外部质量评分器 HTTP 接入请求无效。",
        "External quality scorer HTTP intake request is invalid.",
        False,
    ),
    "QUALITY_SCORER_INTAKE_RECEIPT_QUERY_REQUIRED": ErrorCodeDefinition(
        "QUALITY_SCORER_INTAKE_RECEIPT_QUERY_REQUIRED",
        400,
        False,
        "外部质量评分器接入 receipt 查询缺少必要条件。",
        "External quality scorer intake receipt query requires full scope.",
        False,
    ),
    "QUALITY_SCORER_INTAKE_RECEIPT_NOT_FOUND": ErrorCodeDefinition(
        "QUALITY_SCORER_INTAKE_RECEIPT_NOT_FOUND",
        404,
        False,
        "外部质量评分器接入 receipt 不存在。",
        "External quality scorer intake receipt was not found.",
        False,
    ),
    "QUALITY_CENTER_WORKBENCH_UNAVAILABLE": ErrorCodeDefinition(
        "QUALITY_CENTER_WORKBENCH_UNAVAILABLE",
        400,
        False,
        "Quality Center 工作台暂不可用。",
        "Quality Center workbench is unavailable.",
        False,
    ),
}


def get_contract(contract_id: str) -> ContractRegistryEntry:
    return CONTRACT_REGISTRY[contract_id]


def get_state(machine_value: str) -> StateRegistryEntry:
    return STATE_REGISTRY[machine_value]


def validate_contract_registry(
    registry: Mapping[str, ContractRegistryEntry],
) -> None:
    for contract_id, entry in registry.items():
        if not entry.domain_owner:
            raise AgentOpsError(
                "CONTRACT_OWNER_REQUIRED",
                f"{contract_id} requires a domain owner.",
            )
        if entry.domain_owner not in DOMAIN_OWNERS:
            raise AgentOpsError(
                "CONTRACT_OWNER_REQUIRED",
                f"{contract_id} has an unregistered domain owner.",
            )
        parties = (entry.producer, *entry.consumers)
        if any(party not in CONTRACT_PARTIES for party in parties):
            raise AgentOpsError(
                "CONTRACT_PARTY_UNREGISTERED",
                f"{contract_id} references an unregistered producer or consumer.",
            )
        if not entry.required_fields or not entry.contract_tests:
            raise AgentOpsError(
                "CONTRACT_OWNER_REQUIRED",
                f"{contract_id} requires fields and contract tests.",
            )
        for error_code in entry.error_codes:
            if error_code not in ERROR_CODE_REGISTRY and not _is_existing_error(
                error_code
            ):
                raise AgentOpsError(
                    "CONTRACT_ENUM_UNREGISTERED",
                    f"{contract_id} references unknown error code {error_code}.",
                )


def validate_contract_value(contract_id: str, field_name: str, value: str) -> None:
    entry = get_contract(contract_id)
    allowed = entry.enum_fields.get(field_name)
    if allowed is None:
        raise AgentOpsError(
            "CONTRACT_ENUM_UNREGISTERED",
            f"{field_name} is not a registered enum field.",
        )
    if not isinstance(value, str):
        raise AgentOpsError(
            "CONTRACT_ENUM_UNREGISTERED",
            f"{contract_id}.{field_name} must be a registered string enum value.",
        )
    if value not in allowed:
        raise AgentOpsError(
            "CONTRACT_ENUM_UNREGISTERED",
            f"{value} is not allowed for {contract_id}.{field_name}.",
        )


def validate_state_registry(registry: Mapping[str, StateRegistryEntry]) -> None:
    for machine_value, entry in registry.items():
        if machine_value != entry.machine_value:
            raise AgentOpsError(
                "STATE_DISPLAY_MISMATCH",
                "State registry key and machine_value diverged.",
            )
        expected = entry.expected_display_name or entry.display_name
        if entry.display_name != expected:
            raise AgentOpsError(
                "STATE_DISPLAY_MISMATCH",
                f"{machine_value} display name changed from {expected}.",
            )
        if not entry.display_name or not entry.plain_language_explanation:
            raise AgentOpsError(
                "STATE_DISPLAY_MISMATCH",
                f"{machine_value} requires user-facing state text.",
            )


def contract_registry_hash(registry: Mapping[str, ContractRegistryEntry]) -> str:
    payload = {
        contract_id: entry.to_stable_dict()
        for contract_id, entry in sorted(registry.items())
    }
    serialized = json.dumps(payload, ensure_ascii=False, sort_keys=True)
    return hashlib.sha256(serialized.encode("utf-8")).hexdigest()


def _is_existing_error(error_code: str) -> bool:
    prefixes = (
        "POLICY_",
        "GRANT_",
        "APPROVAL_",
        "RAW_ACCESS_",
        "EVIDENCE_",
        "HEALTH_",
        "RUNTIME_",
        "TRACE_",
        "GUARDRAIL_",
    )
    return error_code.startswith(prefixes)
